name: Test

on:
  issue_comment:
    types: [created]

jobs:
  lint:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '$FIX') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: stefanzweifel/git-auto-commit-action@v4
